#!/usr/bin/env bash
# Script that will display information about subdomains.

# Displays information about a subdomain
display_info() {
    local domain="$1"
    local subdomain="$2"
    
    if [ -z "$subdomain" ]; then
        # Default subdomains
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi
    
    for sub in "${subdomains[@]}"; do
        # Using dig to get DNS information and awk to parse it
        dig_output=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ {getline; print}')
        
        # Extracting record type and destination IP
        record_type=$(echo "$dig_output" | awk '{print $4}')
        destination=$(echo "$dig_output" | awk '{print $5}')
        
        # Displays the information
        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}
# Checks for the correct number of arguments
if [ $# -lt 1 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
domain="$1"
subdomain="$2"
display_info "$domain" "$subdomain"
