#!/usr/bin/env bash
# Updating the package
sudo apt-get update && sudo apt-get upgrade -y

# Install Nginx
sudo apt-get install nginx  -y

# Configure Nginx to listen on port 80
sudo ufw allow 'Nginx HTTP'

# Create a basic HTML file with the required content
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx
sudo /etc/init.d/nginx restart
