#!/usr/bin/env bash
# Script that displays a list of currently running processes
# It shows all processes, for all users including those that might not have a TTY
# Display a user oriented format
# And it shows process hierachy

ps -a -x -u -f
