#!usr/bin/env bash
# script 101-manage_my_process that manages manage_my_process

PID_FILE="/var/run/my_process.pid"
PROGRAM="/path/to/manage_my_process"

start() {
	if [ -f $PID_FILE ]; then
		echo "manage_my_process is already running."
		exit 1
	fi
	
	$PROGRAM &
	echo $! > $PID_FILE
	echo "manage_my_process started."
}

stop() {
	if [ ! -f $PID_FILE ]; then
		echo "manage_my_process is not running."
		exit 1
	fi
	kill $(cat $PID_FILE)
	rm $PID_FILE
	echo "manage_my_process stopped."
}

restart() {
	stop
	start
	echo "manage_my_process restarted."
}

case $1 in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
