#!usr/bin/env bash
# A script that extends previous exercise command and displays line containg the bash word allowing you to display the PID of your bash process easily
# Do not use pgrep
# Shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
