#!/usr/bin/env bash
# A script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
# use the while loop display the first 70 lines using the head command.

hours=0
minutes=1
count=0

while [ $hours -lt 13 ] && [ $minutes -lt 60 ] && [ $count -lt 70 ]; do
    printf "%02d:%02d\n" $hours $minutes

    minutes=$((minutes + 1))
    if [ $minutes -eq 60 ]; then
        minutes=0
        hours=$((hours + 1))
    fi

    count=$((count + 1))
done | head -n 70
