#!/usr/bin/env bash
# A script that displays the content of the current directory
# in a list format
# use the for loop and do not display hidden files

# Loop through the files in the current directory
for file in *; do
    # Check if the file is not hidden and is a regular file
    if [[ ! "$file" == .* && -f "$file" ]]; then
        # Extract the part of the name after the first dash
        name=$(echo "$file" | cut -d'-' -f2-)
        # Display the name
        echo "$name"
    fi
done

