#!/usr/bin/env bash
# script that configures an Ubuntu server and Change your home IP

# Backup the original hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Update localhost entry in hosts file
sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts

# Update facebook.com entry in hosts file
sudo sed -i 's/157.240.11.35/8.8.8.8/g' /etc/hosts

# Flush DNS cache
sudo /etc/init.d/networking restart

echo "Configuration complete."

