#!/usr/bin/env bash
# A script that Shows attached IPs
# Retrieve all active IPv4 addresses using the 'ip' command
ipv4_addresses=$(ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}')

# Loop through each IP address and display them
for ip_address in $ipv4_addresses; do
  echo "$ip_address"
done
