#!/usr/bin/env bash
# Bash script that creates an RSA key pair.
# private key must be school
# Number of bits in the created key to be created 4096
# key protected by the passphrase betty
ssh-keygen -t rsa -b 4096 -f school -N betty
